### ISSUE TITLE
Roselia lists "zzlinggleam" as a learned move in `//learn Roselia`

### ISSUE THREAD

**Issue by Stalruth** [JsKingBoo/SableyeBot3#13]
The //learn command returns a move called "zzlinggleam" when called with `//learn Roselia` or `//learn Roserade`.  This does not happen with other Pokemon and Dazzling Gleam is properly listed in Roselia and Roserade's learnset listings.

**Comment by JsKingBoo** [comment]
This is actually a typo in Showdown's database (under `roselia` in `/data/learnsets.js`)

https://raw.githubusercontent.com/smogon/pokemon-showdown/b0e649972bbd043e0d84ee23186cedad37942b47/data/learnsets.js
