### ISSUE TITLE
throw new TypeError(`Exported property 'Formats' from "./config/formats.js" must be an array`)

### ISSUE THREAD

**Issue by tickletehpickle** [JsKingBoo/SableyeBot3#2]
After following the instructions on installing the bot, I'm getting this issue.. Unless I'm missing some dependencies, but I'm stuck in this bind..
![putty_2018-04-22_16-42-52](https://i.imgur.com/RvUH80V.png)

**Comment by JsKingBoo** [comment]
It appears that SableyeBot is using an older version of `dex.js`, and the new version breaks the bot. Will look into this.

I apologize for the late response; I have been busy with school

**Comment by JsKingBoo** [comment]
I have updated the installation instructions in the README. Hopefully this resolves the issue, and let me know if you still encounter problems.
