### ISSUE TITLE
Event command not working

### ISSUE THREAD

**Issue by elwaiqi** [JsKingBoo/SableyeBot3#20]
Whenever the event command is run, returns the help instead of the info requested.

For example:
`//event Rayquaza, 1`

Returns:
```//event <Pokemon name>, [event ID]
Number of events a Pokemon has, or the set details of a specific event.
Aliases: events
Flags: --gen
For more information, use //help event```

**Comment by HectorDMS** [comment]
Hi.
I also have the same problem with the bot, when I wanted to see the event of a tapu, the same message came to me.

**Comment by Stalruth** [comment]
Thanks to both of you for raising this issue; this will be fixed when the bot next reboots.
