### ISSUE TITLE
//learn <move name> doesn't work

### ISSUE THREAD

**Issue by elwaiqi** [JsKingBoo/SableyeBot3#21]
When using the `<//learn <move name>`, it outputs this instead of the Pokémon that can learn that move:

```
//learn (<Pokémon name>[, <move name>]...)|<move name>
Learnset of a Pokémon, how a Pokémon learns a move(s), or Pokémon than can learn a move.
Aliases: learnset
Flags: --verbose, --cap, --vgc, --natdex, --gen
For more information, use //help learn
```

**Comment by Stalruth** [comment]
Thanks for your report.

I'm looking into this, in the meantime `//filter move=<move name>` accomplishes the same use case.
