### ISSUE TITLE
//weakness (<type 1>, [type 2]) doesn't work

### ISSUE THREAD

**Issue by Asmod96** [JsKingBoo/SableyeBot3#22]
When using `//weakness (<type 1>, [type 2])`, bot outputs info about command's grammar instead of weakness for given type combination:
```
//weakness <Pokemon name>|(<type 1>, [type 2])
Provides a Pokemon's resistances, weaknesses, and immunities, ignoring abilities.
Aliases: weak
Flags: --inverse, --gen
For more information, use //help weakness```

**Comment by Asmod96** [comment]
It properly gives information about pokemon's weakness though.

**Comment by Stalruth** [comment]
Thanks for the report, fixed.

The new version should be deployed soon.
