### ISSUE TITLE
Errors in README.md regarding fresh installation

### ISSUE THREAD

**Issue by Stalruth** [JsKingBoo/SableyeBot3#6]
There are two issues in README.md with respect to a fresh installation of the bot.

1. The Pokemon Showdown Server needs to be built first (`./build`) for the files needed from `sim/` to be generated.
2. As of Zarel/Pokemon-Showdown-Client@84e76c :

    >Stop tracking minidex in Git
    >
    >These files are now autogenerated by the build scripts, and depend
    >on files not even present on GitHub anyway.
    >
    >(The minidex is a database of height/width for PS's animated GIF
    >sprites, for use by the animation engine. It also contains dex numbers
    >for use by pokemon icon spritesheets.)

    This means that //sprite and //furretturretsprite won't work off a fresh install.

**Comment by JsKingBoo** [comment]
uh oh I don't know how to fix this

Well actually I do have a vague idea, I need to generate them myself. I only depend on the existence of the female flag IIRC. Alternatively I can hijack the build script. Not sure how I want to approach this at the moment.

**Comment by Stalruth** [comment]
Alrighty so downloading the Client and doing a full build solves getting the files from the `sim/` directory of the server, as the full build downloads and builds the server, although the js files are locates in `Client_dir/data/Pokemon-Showdown/.sim-data`.

Getting the sprites is a slightly thornier issue.  You could download the sprites from [here (XY)](https://play.pokemonshowdown.com/sprites/xyani/) and [here (BW)](https://play.pokemonshowdown.com/sprites/bwani/) but then you might as well download [pokedex-mini.js](https://play.pokemonshowdown.com/data/pokedex-mini.js) and its [BW version](https://play.pokemonshowdown.com/data/pokedex-mini-bw.js) manually.  The alternative is to change the //sprite and //furretturretsprite commands to check for the existence of female sprites, which is likely a better call.

**Comment by Stalruth** [comment]
I've been looking at //sprite for some time and the best solution is probably to download the files from https:play.pokemonshowdown.com as the structure of the commands seems to not be friendly to async functions, which is the only other way I can see this working.

**Comment by JsKingBoo** [comment]
Fixed by #7
